#!/usr/bin/env python

"""
Initialize database tables for the task queue
"""

from trigger.acl.models import create_tables, confirm_tables
from trigger.conf import settings
from trigger.utils.cli import proceed

def print_settings(settings):
    attrs = [a for a in dir(settings) if a.startswith('DATABASE_')]
    max_w = max(len(a) for a in attrs)
    for a in attrs:
        #print a, getattr(settings, a)
        print '%s: %s' % (a.rjust(max_w), getattr(settings, a))

def main():
    print 'We are going to initialize the database with the following settings:'
    print_settings(settings)
    proceed()
    print 'Creating tables...'

    create_tables()
    if confirm_tables():
        print '\nGood to go!'
    else:
        print '\nSomething went wrong. Check the settings and try again!'

if __name__ == '__main__':
    main()
